### ISSUE TITLE
Not working with pre-commit

### ISSUE THREAD

**Issue by yajo** [KyleKing/copier-template-tester#27]
**Describe the bug**

For some reason, latest release marks everything under `.ctt/` to be deleted after running the pre-commit hook.

**To Reproduce**

```bash

(master) $ git status
On branch master
nothing to commit, working tree clean

(master) $ ls -lA
total 8
-rw-r--r-- 1 gitpod gitpod  36 Nov  6 08:50 ctt.toml
drwxr-xr-x 8 gitpod gitpod 184 Nov  6 08:58 .git
-rw-r--r-- 1 gitpod gitpod 129 Nov  6 08:48 .pre-commit-config.yaml

(master) $ cat ctt.toml 
[defaults]
[output.".ctt/defaults"]

(master) $ cat .pre-commit-config.yaml 
repos:
  - repo: https://github.com/KyleKing/copier-template-tester
    rev: 2.0.0
    hooks:
      - id: copier-template-tester

(master) $ pre-commit install
pre-commit installed at .git/hooks/pre-commit

(master) $ pre-commit run -a
copier-template-tester...................................................Passed

(master) $ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .ctt/

nothing added to commit but untracked files present (use "git add" to track)

(master) $ ls -lAR .ctt/
.ctt/:
total 0
drwxr-xr-x 2 gitpod gitpod 53 Nov  6 08:59 defaults

.ctt/defaults:
total 8
-rw-r--r-- 1 gitpod gitpod  36 Nov  6 08:59 ctt.toml
-rw-r--r-- 1 gitpod gitpod 129 Nov  6 08:59 .pre-commit-config.yaml

(master) $ git add -A

(master) $ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   .ctt/defaults/.pre-commit-config.yaml
        new file:   .ctt/defaults/ctt.toml


(master) $ git commit 
copier-template-tester...................................................Failed
- hook id: copier-template-tester
- exit code: 1

Starting Copier Template Tester for /workspace/copier-template-tester/test
Note: If files were modified, pre-commit will report a failure.

Using `copier` to create: .ctt/defaults
Traceback (most recent call last):
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/bin/ctt", line 8, in <module>
    sys.exit(run_cli())
             ^^^^^^^^^
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/copier_template_tester/main.py", line 60, in run_cli
    run(base_dir=args.base_dir, check_untracked=args.check_untracked)
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/copier_template_tester/main.py", line 37, in run
    write_output(src_path=input_path, dst_path=base_dir / output_path, data=defaults | data)
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/copier_template_tester/_write_output.py", line 141, in write_output
    copier.run_copy(str(src_path), dst_path, **kwargs)
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/copier/main.py", line 980, in run_copy
    with Worker(src_path=src_path, dst_path=Path(dst_path), **kwargs) as worker:
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/copier/main.py", line 205, in __exit__
    raise value
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/copier/main.py", line 981, in run_copy
    worker.run_copy()
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/copier/main.py", line 736, in run_copy
    self._print_message(self.template.message_before_copy)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.pyenv/versions/3.12.0/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/copier/template.py", line 325, in message_before_copy
    return self.config_data.get("message_before_copy", "")
           ^^^^^^^^^^^^^^^^
  File "/home/gitpod/.pyenv/versions/3.12.0/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/copier/template.py", line 272, in config_data
    result = filter_config(self._raw_config)[0]
                           ^^^^^^^^^^^^^^^^
  File "/home/gitpod/.pyenv/versions/3.12.0/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/copier/template.py", line 231, in _raw_config
    for p in self.local_abspath.glob("copier.*")
             ^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.pyenv/versions/3.12.0/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/copier/template.py", line 478, in local_abspath
    result = Path(clone(self.url_expanded, self.ref))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/copier/vcs.py", line 190, in clone
    git(
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/plumbum/commands/base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/plumbum/commands/base.py", line 252, in run
    return p.run()
           ^^^^^^^
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/plumbum/commands/base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/plumbum/commands/processes.py", line 299, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/plumbum/commands/processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/home/gitpod/.cache/pre-commit/repo1gssc97b/py_env-python3/lib/python3.12/site-packages/plumbum/machines/base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | /usr/lib/git-core/git --git-dir=.git --work-tree=/workspace/copier-template-tester/test commit -m 'Copier automated commit for draft changes' --no-verify --no-gpg-sign
Stdout:       | On branch master
              | Your branch is up to date with 'origin/master'.
              | 
              | nothing to commit, working tree clean



(master) $ git status
On branch master
nothing to commit, working tree clean

(master) $ ls -lA
total 8
drwxr-xr-x 3 gitpod gitpod  22 Nov  6 08:59 .ctt
-rw-r--r-- 1 gitpod gitpod  36 Nov  6 08:50 ctt.toml
drwxr-xr-x 8 gitpod gitpod 184 Nov  6 08:59 .git
-rw-r--r-- 1 gitpod gitpod 129 Nov  6 08:48 .pre-commit-config.yaml

(master) $ ls -lAR .ctt/
.ctt/:
total 0
drwxr-xr-x 2 gitpod gitpod 6 Nov  6 08:59 defaults

.ctt/defaults:
total 0
```

**Expected behavior**

When issuing the commit, only changed files should make a conflict.

**Comment by KyleKing** [comment]
Sorry that you've run into another bug. I have a busy week, but I'll have time this weekend to debug and release a fix

**Comment by KyleKing** [comment]
Could you share the contents of the `copier.yml` file?

**Comment by KyleKing** [comment]
I ended up haivng some time. I think this issue should be resolved in v2.0.1.

When there is no `copier.yaml` file, the directory isn't created, which avoids the potential for deletion later:

```
.  > mkcd ctt-27
./ctt-27  > git init
Initialized empty Git repository in ./ctt-27/.git/
./ctt-27 main≢  ~1  +2 > lzg
copier-template-tester...................................................Passed
[main (root-commit) bb9f32b] add
 2 files changed, 7 insertions(+)
 create mode 100644 .pre-commit-config.yaml
 create mode 100644 ctt.toml

Press enter to return to lazygit

./ctt-27 main≢ > pre-commit run --all-files
copier-template-tester...................................................Passed
./ctt-27 main≢ > lsa
 .git   .pre-commit-config.yaml   ctt.toml
./ctt-27 main≢ > bat .pre-commit-config.yaml
───────┬────────────────────────────────────────────────────────────────────────
       │ File: .pre-commit-config.yaml
───────┼────────────────────────────────────────────────────────────────────────
   1   │ repos:
   2   │   - repo: https://github.com/KyleKing/copier-template-tester
   3   │     rev: 2.0.1
   4   │     hooks:
   5   │       - id: copier-template-tester
───────┴────────────────────────────────────────────────────────────────────────
./ctt-27 main≢ > bat ctt.toml
───────┬────────────────────────────────────────────────────────────────────────
       │ File: ctt.toml
───────┼────────────────────────────────────────────────────────────────────────
   1   │ [defaults]
   2   │ [output.".ctt/defaults"]
───────┴────────────────────────────────────────────────────────────────────────
```

Let me know if you think this case should be handled differently or if I misunderstood this issue.

**Comment by yajo** [comment]
Still failing: https://github.com/KyleKing/copier-template-tester/issues/28
